"""dicts

Revision ID: 7fdc70ed03cd
Revises: 22683f0d5d42
Create Date: 2025-11-22 21:18:33.958708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdc70ed03cd'
down_revision = '22683f0d5d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('statuses',
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statuses')
    op.drop_table('categories')
    # ### end Alembic commands ###
