"""Initial migration

Revision ID: ce8f76f6f9fb
Revises: 
Create Date: 2025-11-15 03:56:23.536976

"""
from alembic import op
import sqlalchemy as sa
from flask import current_app

from app.models import User

# revision identifiers, used by Alembic.
revision = 'ce8f76f6f9fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    user_table = op.create_table('users',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('email')
    )
    op.bulk_insert(
        roles_table, [
            {
                'name': 'admin',
            },
            {
                'name': 'editor',
            }
        ])
    conn = op.get_bind()
    admin = User(name="admin", email="admin@localhost", role_id=1, password=current_app.config["ADMIN_PASS"])
    op.bulk_insert(
        user_table, [
            {
                'name': admin.name,
                'email': admin.email,
                'password_hash': admin.password_hash,
                'role_id': admin.role_id,
            },
        ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
