apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cool-service
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.nano-byte.net
      chart: generic-service
      targetRevision: 1.10.0
      helm:
        values: |
          fullname: 'generic-service'
  
          image:
            repository: njuhaandrej/my-cool-service
            tag: latest
          envFrom:
            - secretRef:
                name: my-cool-service-secret
          persistence:
            enabled: true
            size: 20M
            mountPath: /app/instance
          
          ingress:
            enabled: true
            protocol: http
            domains:
              - my-cool-service
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: my-cool-service
                    port:
                      number: 5000

    - repoURL: https://kiwigrid.github.io
      chart: any-resource
      targetRevision: 0.1.0
      helm:
        values: |
          my-cool-service-secret: |-
            apiVersion: v1
            stringData:
              OPA_HOST: opa.opa.svc
              ADMIN_PASS: 12345
            kind: Secret
            metadata:
              name: my-cool-service-secret
            type: Opaque

  destination:
    server: https://kubernetes.default.svc
    namespace: my-cool-service
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true

