apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cool-service
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.14.0
      helm:
        values: |
          applicationName: 'generic-service'
          deployment:
            image:
              repository: njuhaandrej/my-cool-service
              tag: latest
            persistence:
              enabled: true
              mountPVC: true
              storageSize: 20M
              mountPath: /app/instance
            envFrom:
              my-cool-service-secret:
                type: secret
          service:
            type: NodePort
            ports:
              - port: 5555
                name: http
                protocol: TCP
                targetPort: 5000
          secret:
            enabled: true
            files:
              my-cool-service-secret:
                data:
                  OPA_HOST: "opa.opa.svc"
                  ADMIN_PASS: "12345"

#    - repoURL: https://kiwigrid.github.io
#      chart: any-resource
#      targetRevision: 0.1.0
#      helm:
#        values: |
#          my-cool-service-secret: |-
#            apiVersion: v1
#            stringData:
#              OPA_HOST: opa.opa.svc
#              ADMIN_PASS: 12345
#            kind: Secret
#            metadata:
#              name: my-cool-service-secret
#            type: Opaque

  destination:
    server: https://kubernetes.default.svc
    namespace: my-cool-service
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true

