apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://open-policy-agent.github.io/kube-mgmt/charts
      chart: opa-kube-mgmt
      targetRevision: 9.2.2
      helm:
        values: |
          opa:
            decision_logs:
              console: true
          useHttps: false
          mgmt:
            startupProbe:
              httpGet:
                path: /health
                port: 8181
                scheme: HTTP
          logLevel: info
          bootstrapPolicies:
            my-cool-service: |-
              package httpapi.authz
              
              default allow := false
              
              allow if {
                  input.method == "GET"
                  input.path == ["api", "users"]
                  input.role in ["admin", "editor"]
              }
              
              allow if {
                  input.method == "POST"
                  input.path == ["api", "users"]
                  input.role == "admin"
              }
  
          authz:
              mgmtToken:
                 secretName: mgmt-token

    - repoURL: https://charts.alekc.dev
      chart: any-resource
      targetRevision: 0.1.0
      helm:
        values: |
          mgmt-token: |-
            apiVersion: v1
            stringData:
              mgmtToken: 8VcIglGoTbUWIA78DLITCuw5KhxfhohGWiSVxDGXS4spKwhAvjyIMrwd31695GYk
            kind: Secret
            metadata:
              name: mgmt-token
              annotations:
                replicator.v1.mittwald.de/replicate-to: "my-cool-service"
            type: Opaque

  destination:
    server: https://kubernetes.default.svc
    namespace: opa
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true

